import { MainLayout } from '@/components/layout';
import Head from 'next/head';
import { NextPageWithLayout } from '@/models';

interface HomeProps {}

const Home: NextPageWithLayout<HomeProps> = () => {
  return (
    <>
      <Head>
        <title>Navbar Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen flex items-center justify-center text-center">
        <h1 className="text-5xl font-bold">Home Page</h1>
      </div>
    </>
  );
};

Home.Layout = MainLayout;

export default Home;
